import reflex as rx
from keikodev.componentes.linkbutton import linkbutton
from keikodev.componentes.title import title
from keikodev.styles.styles import Size as Size
import keikodev.views.constants as constants
from keikodev.routes import Route


def dev_links()-> rx.Component:
        return rx.chakra.vstack(
        title("Recursos para programación"),
                linkbutton("Reflex",
                        "Entorno para programación WEB desde Python con hosting incluido (Alpha)",
                        "/img/laptop-code-solid.svg",
                        constants.REFLEX_URL,
                ),
                linkbutton("MoureDev",
                        "El maestro. Todo tipo de cursos relacionados con la programación",
                        "/img/python.svg",
                        constants.MOUREDEV_URL,
                ),
                linkbutton("Railway",
                        "Servicio gratuito para ejecutar backend",
                        "/img/python.svg",
                        constants.RAILWAY_URL,
                ),
                linkbutton("Fl0",
                        "Servicio gratuito para ejecutar backend",
                        "/img/python.svg",
                        constants.FL_URL,
                ),
                linkbutton("Framework Flet",
                "Desarrollo de aplicaciones multiplataforma con python",
                "/img/windows.svg",
                constants.FLET_URL,
                ),
                linkbutton("Programación con Pseint",
                "Curso para conocer las bases de la programación mediante el uso de Pseint para luego empezar a programar en Python",
                "/img/graduation-cap-solid.svg",
                constants.CURSO_PSEIN_URL,
                ),
                linkbutton("W3School",
                        "Tutorial CSS",
                        "/img/css3.svg",
                        constants.W3SCHOOLS_URL,
                ),
                linkbutton("MDN",
                        "Tutoriales para desarrollo WEB",
                        "/img/database-solid.svg",
                        constants.MDM_URL,
                ),
                linkbutton("React",
                        "Librería con recursos para desarrollo",
                        "/img/window-restore-regular.svg",
                        constants.REACT_URL,
                ),
                linkbutton("Chakra",
                        "Recursos para desarrollo WEB",
                        "/img/layer-group-solid.svg",
                        constants.CHAKRA_URL,
                ),
                linkbutton("Ant Design",
                        "Recursos para desarrollo WEB",
                        "/img/code-solid.svg",
                        constants.ANTDESIGN_URL,
                ),
                linkbutton("Radix UI",
                        "Recursos para desarrollo WEB",
                        "/img/code-branch-solid.svg",
                        constants.RADIX_URL,
                ),
                linkbutton("IT Tools",
                        "Web de herramientas para programación",
                        "/img/database-solid.svg",
                        constants.ITTOOLS_URL,
                ),
                linkbutton("Animate CSS",
                        "Librería CSS para incorporar animaciones",
                        "/img/css3.svg",
                        constants.ANIMATECSS_URL,
                ),
                linkbutton("UI Colors",
                        "Página que nos ayuda a crear la paleta de colores para tu web",
                        "/img/css3.svg",
                        constants.UICOLORS_URL,
                ),
                linkbutton(is_external=False),

        width = "100%",
        spacing=Size.MEDIUM.value,
        )