import reflex as rx
from keikodev.componentes.linkbutton import linkbutton
from keikodev.componentes.title import title
from keikodev.styles.styles import Size as Size
import keikodev.views.constants as constants

def links()-> rx.Component:
    return rx.vstack(
        title("Recursos para programación"),
        linkbutton("Desarrollo",
                   "Páginas relacionadas con el desarrollo de aplicaciones",
                   "icons/dev.svg",
                   constants.MOUREDEV_URL),
        linkbutton("Herramientas gráficas",
                   "Herramientas gráficas para Desarrollos",
                   "icons/dev.svg",
                   constants.FOTOR_URL),
        linkbutton('GitHub', 
                   "Mi repositorio en Git Hub", 
                   "icons/dev.svg",
                   constants.GITHUB_URL),
        linkbutton('Tips e instrucciones más usadas', 
                   "Como tengo memoria de pez, este será mi bloc de notas para", 
                   "icons/dev.svg",
                   constants.DEFAULT_URL),
        
        title("Otras ideas"),
        linkbutton("Configuración de kodi",
                   "Apartado destinado a mantener la configuración de kodi",
                   "icons/dev.svg",
                   constants.DEFAULT_URL),

        linkbutton("Biblioteca de imágenes",
                   "Crear biblioteca de imágenes con fotografía propia",
                   "icons/dev.svg",
                   constants.DEFAULT_URL),

        linkbutton('Biblioteca WOW', 
                   "Enlaces para fanáticos del WOW que no te puedes perder.", 
                   "icons/dev.svg",
                   constants.DEFAULT_URL),
        
        linkbutton('Cyber Seguridad', 
                   "Casos comunes de ciber ataques", 
                   "icons/dev.svg",
                   constants.DEFAULT_URL),

        title("Backup"),
        linkbutton("Reflex Dev",
                   "Para crear páginas web con Python",
                   "icons/dev.svg",
                   constants.REFLEX_URL),
        linkbutton("Google",
                   "Buscador universal",
                   "icons/dev.svg",
                   constants.GOOGLE_URL),
        linkbutton("Mouredev", 
                   "El Maestro",
                   "icons/dev.svg", 
                   constants.MOUREDEV_URL),
        linkbutton('W3Schools', 
                   "Aprende CSS", 
                   "icons/dev.svg",
                   constants.W3SCHOOLS_URL),
        linkbutton('GitHub', 
                   "Mi repositorio en Git Hub",
                   "icons/dev.svg", 
                   constants.GITHUB_URL),
        title("Contacto"),
        linkbutton("Email",
                   constants.EMAIL,
                   "icons/dev.svg",
                   f"mailto:{constants.EMAIL}"),
        width = "100%",
        spacing=Size.MEDIUM.value,
    )