from enum import Enum

class Route(Enum):
    INDEX = "/"
    DEV = "/dev"
    CONSTR = "/construccion"
    UTILS_IMAGES = "/retoque"
    KODI = "/kodi"
    KODI_PC = "/kodi_pc"
    KODI_LUAR = "/luar"
    KODI_ADDONS = "/addons"
    ESTAFAS = "/estafas"
    GALERIA = "/galeria"
    GALERIA_NASA = "/galeria_nasa"
    EMULATOR = "/emulator"
    COOKIES = "/cookies"
    PRIVACIDAD = "/privacidad"
    CURSOS = "/cursos"
    TRUCOS = "/trucos"
    KODI_TRUCOS = "/koditrucos"
    KODI_KODIVERTIDO = "/kodi/kodivertido"
    KODI_CRISTALAZUL = "/kodi/cristalazul"
    KODI_TVCHOPO = "/kodi/tvchopo"
    KODI_BALANDRO = "/kodi/balandro"
    KODI_ARROWNEGRA = "/kodi/arrownegra"
    COCINA = "/cocina"
    