from enum import Enum

class Route(Enum):
    INDEX = "/"
    DEV = "/dev"
    CONSTR = "/construccion"
    UTILS_IMAGES = "/retoque"
    ESTAFAS = "/estafas"
    GALERIA = "/galeria"
    GALERIA_NASA = "/galeria_nasa"
    GALERIA_NASA_VIDEO = "galeria_nasa_video"
    EMULATOR = "/emulator"
    COOKIES = "/cookies"
    PRIVACIDAD = "/privacidad"
    CURSOS = "/cursos"
    TRUCOS = "/trucos"
    COCINA = "/cocina"
    KEIKO = "/keiko"
    KEIKO_INTERES = "/keiko/interes"
    KEIKO_CUIDADOS = "/keiko/cuidados"
    SPACEX = "/SpaceX"
    SPACEX_STARSHIP = "/SpaceX/StarShip"
    LOGIN = "/login"
    LAUNCH_PAGE = "/launches"
    IA_TOOLS = "/iatools"
    ABOUT = "/about"
    KODI = "/kodi"
    KODI_PC = "/kodi_pc"
    KODI_LUAR = "/luar"
    KODI_ADDONS = "/addons"
    KODI_TRUCOS = "/koditrucos"
    KODI_KODIVERTIDO = "/kodi/kodivertido"
    KODI_CRISTALAZUL = "/kodi/cristalazul"
    KODI_TVCHOPO = "/kodi/tvchopo"
    KODI_BALANDRO = "/kodi/balandro"
    KODI_ARROWNEGRA = "/kodi/arrownegra"
    

    
    